# Generated by Django 5.2.3 on 2025-07-19 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_agent_quote'),
        ('vendors', '0019_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='has_variable_pricing',
            field=models.BooleanField(default=False, help_text='True for venues that require a custom quote (e.g., SCC).'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured locations appear at the top.'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.region'),
        ),
    ]
