# Generated by Django 5.2.3 on 2025-07-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_location_created_at_alter_location_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='budget_estimate_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='budget_estimate_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_indoor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_outdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='organizer_notes',
            field=models.TextField(blank=True, help_text='Internal notes for the event organizer'),
        ),
        migrations.AddField(
            model_name='location',
            name='parking_info',
            field=models.CharField(blank=True, help_text="e.g., 'On-site parking for 50 cars'", max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='preferred_dates',
            field=models.JSONField(blank=True, default=list, help_text="A list of preferred date ranges, e.g., [{'start': '2024-12-20', 'end': '2024-12-25'}]"),
        ),
        migrations.AddField(
            model_name='location',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='locations.amenity'),
        ),
    ]
