# Generated by Django 5.2.3 on 2026-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('new_bid', 'New Bid'), ('bid_accepted', 'Bid Accepted'), ('bid_declined', 'Bid Declined'), ('bid_countered', 'Bid Countered'), ('booking_request', 'Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled')], max_length=32),
        ),
    ]
