# Generated by Django 5.1.4 on 2024-12-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('testimonial', models.TextField(blank=True)),
                ('portfolio', models.ImageField(upload_to='portfolio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.category')),
            ],
        ),
    ]
