# Generated by Django 5.1.4 on 2024-12-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_serviceprovider_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProvider',
            new_name='Vendor',
        ),
    ]
