# Generated by Django 5.2.3 on 2025-06-29 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_service_price_alter_service_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
