# Generated by Django 5.2.3 on 2025-07-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_amenity_region_review_rating_service_amenities_and_more'),
        ('vendors', '0014_service_similar_services'),
    ]

    operations = [
    ]
