# Generated by Django 5.2.3 on 2025-07-19 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_is_draft'),
        ('vendors', '0014_service_similar_services'),
        ('vendors', '0018_service_available_timeslots_service_max_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bookings', to='events.event'),
        ),
    ]
