# Generated by Django 5.2.3 on 2025-07-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('events', '0008_eventvendor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistbooking',
            unique_together={('artist', 'event', 'start_time')},
        ),
    ]
