# Generated by Django 5.2.3 on 2025-07-09 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artistportfolioitem_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='artists.artist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
