# Generated by Django 5.2.3 on 2025-07-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artistpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistportfolioitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
