# Generated by Django 5.2.3 on 2025-07-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_created_at_alter_artist_updated_at'),
        ('events', '0014_event_is_draft'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistbooking',
            unique_together={('artist', 'event')},
        ),
        migrations.AddField(
            model_name='artist',
            name='availability',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"2024-07-25": "unavailable"}'),
        ),
        migrations.AddField(
            model_name='artist',
            name='booking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per performance or hourly rate.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='artistbooking',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='artistbooking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='artistbooking',
            name='start_time',
        ),
    ]
