# Generated by Django 5.2.3 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0008_alter_artistbooking_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="booking_fee_max",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="booking_fee_min",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="general_ticket_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="tour_cities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artist",
            name="tour_clubs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artist",
            name="tour_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="tour_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
