# Generated by Django 5.1.4 on 2026-02-14 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0008_alter_artistbooking_unique_together_and_more'),
        ('events', '0017_event_published_at_event_status_alter_event_is_draft'),
        ('locations', '0007_amenity_location_budget_estimate_max_and_more'),
        ('vendors', '0019_booking_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=16)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('local_start_time', models.TimeField()),
                ('local_end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_start_at', models.DateTimeField()),
                ('requested_end_at', models.DateTimeField()),
                ('attendee_count', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('provider_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_requests', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('attendee_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reschedule_pending', 'Reschedule Pending'), ('disputed', 'Disputed'), ('expired', 'Expired')], default='hold', max_length=24)),
                ('source', models.CharField(choices=[('instant', 'Instant'), ('request', 'Request'), ('admin_override', 'Admin Override')], max_length=24)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reschedule_requested_start_at', models.DateTimeField(blank=True, null=True)),
                ('reschedule_requested_end_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_cancelled_v2', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_bookings', to='events.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_created_v2', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking', to='scheduling.bookingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('venue', 'Venue'), ('artist', 'Artist'), ('vendor', 'Vendor')], max_length=16)),
                ('display_name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('artist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_resource', to='artists.artist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_resources', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_resource', to='vendors.vendor')),
                ('venue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_resource', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('organizer', 'Organizer'), ('resource', 'Resource'), ('admin', 'Admin')], max_length=16)),
                ('calendar_type', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('booked', 'Booked'), ('blackout', 'Blackout'), ('hold', 'Hold')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='scheduling.booking')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='events.event')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='scheduling.bookingrequest')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='scheduling.marketplaceresource')),
            ],
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='scheduling.marketplaceresource'),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.marketplaceresource'),
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('capacity_total', models.PositiveIntegerField(default=1)),
                ('capacity_reserved', models.PositiveIntegerField(default=0)),
                ('is_bookable', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_slots', to='scheduling.availabilityrule')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduling.marketplaceresource')),
            ],
        ),
        migrations.AddField(
            model_name='availabilityrule',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='scheduling.marketplaceresource'),
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('blackout', 'Blackout'), ('override', 'Override')], max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_available_override', models.BooleanField(default=False)),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='scheduling.marketplaceresource')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=128)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='scheduling__status_126506_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='scheduling__aggrega_4f0980_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourcePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_mode', models.CharField(choices=[('instant', 'Instant'), ('approval_required', 'Approval Required'), ('hybrid', 'Hybrid')], default='approval_required', max_length=32)),
                ('min_notice_hours', models.PositiveIntegerField(default=24)),
                ('max_horizon_days', models.PositiveIntegerField(default=365)),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0)),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0)),
                ('cancellation_window_hours', models.PositiveIntegerField(default=24)),
                ('default_capacity', models.PositiveIntegerField(default=1)),
                ('allow_reschedule', models.BooleanField(default=True)),
                ('require_message_for_request', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='scheduling.marketplaceresource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('is_admin_override', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='scheduling__target__526bb6_idx'), models.Index(fields=['created_at'], name='scheduling__created_5a7392_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'endpoint', 'key'), name='uniq_idempotency_owner_endpoint_key')],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceresource',
            index=models.Index(fields=['resource_type', 'is_active'], name='scheduling__resourc_05052b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceresource',
            index=models.Index(fields=['owner', 'is_active'], name='scheduling__owner_i_0cdea2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['actor_type', 'actor_user', 'start_at'], name='scheduling__actor_t_c4c730_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['resource', 'start_at', 'end_at'], name='scheduling__resourc_d546c6_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event', 'start_at', 'end_at'], name='scheduling__event_i_fe1ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['resource', 'status'], name='scheduling__resourc_adc815_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['organizer', 'status'], name='scheduling__organiz_5cfe89_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['event', 'status'], name='scheduling__event_i_c7438d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['expires_at'], name='scheduling__expires_2e9c96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'status'], name='scheduling__resourc_60467c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'start_at', 'end_at'], name='scheduling__resourc_21c634_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organizer', 'status'], name='scheduling__organiz_e51772_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'status'], name='scheduling__event_i_33f18a_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['resource', 'start_at', 'end_at'], name='scheduling__resourc_40b5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['resource', 'is_bookable'], name='scheduling__resourc_21a19f_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('resource', 'start_at', 'end_at'), name='uniq_resource_slot_window'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_reserved__lte', models.F('capacity_total'))), name='capacity_reserved_lte_total'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['resource', 'is_active'], name='scheduling__resourc_229f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['resource', 'effective_start_date'], name='scheduling__resourc_028210_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['resource', 'start_at', 'end_at'], name='scheduling__resourc_50269e_idx'),
        ),
    ]
