# Generated by Django 5.2.3 on 2025-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('vendor', 'Vendor'), ('artist', 'Artist'), ('venue', 'Venue Rep'), ('attendee', 'Attendee')], default='organizer', max_length=10),
        ),
    ]
