# Generated by Django 5.2.3 on 2025-07-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EVENT_ORGANIZER', 'Event Organizer'), ('ARTIST', 'Artist'), ('SERVICE_PROVIDER', 'Service Provider'), ('VENUE_MANAGER', 'Venue Manager'), ('TICKET_BUYER', 'Ticket Buyer')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, to='users.role'),
        ),
    ]
