# Generated by Django 5.2.3 on 2025-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('EVENT_ORGANIZER', 'Event Organizer'), ('ARTIST', 'Artist'), ('SERVICE_PROVIDER', 'Service Provider'), ('VENUE_MANAGER', 'Venue Manager'), ('TICKET_BUYER', 'Ticket Buyer')], max_length=30, unique=True),
        ),
    ]
