# Generated by Django 5.1.4 on 2024-12-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='price_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
