# Generated by Django 5.1.4 on 2024-12-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_serviceprovider_price_range_alter_serviceprovider_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='testimonials',
            new_name='testimonial',
        ),
    ]
