# Generated by Django 5.1.4 on 2024-12-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_guest_count_event_notes_event_partner_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
