# Generated by Django 5.2.3 on 2025-07-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_end_time_event_start_time'),
        ('vendors', '0016_bookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_links', to='events.event')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='vendors.service')),
            ],
        ),
    ]
