# Generated by Django 5.2.3 on 2025-07-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_banner_image_event_end_date_event_organizer_and_more'),
        ('locations', '0002_remove_venuebooking_venue_alter_venuebooking_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
    ]
