# Generated by Django 5.2.3 on 2025-07-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_banner_image_event_end_date_event_organizer_and_more'),
        ('events', '0013_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='If true, this event is a draft and not yet published.'),
        ),
    ]
