# Generated by Django 5.2.3 on 2025-07-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Invite-Only')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_age_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_seated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_buyer',
            field=models.PositiveIntegerField(default=10, help_text='Limits how many tickets one person can buy.'),
        ),
        migrations.AddField(
            model_name='event',
            name='refund_policy',
            field=models.TextField(blank=True, help_text="Stores refund policy details, e.g., 'Full', 'None', or custom text."),
        ),
        migrations.AddField(
            model_name='event',
            name='seating_chart',
            field=models.FileField(blank=True, null=True, upload_to='seating_charts/'),
        ),
        migrations.AddField(
            model_name='event',
            name='tiered_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='If 4true, this event is a draft and not yet published.'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='events.event')),
            ],
        ),
    ]
