# Generated by Django 5.2.3 on 2025-12-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='High level state of the listing that controls organizer actions.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='If true, this event is a draft and not yet published.'),
        ),
    ]
